# -*- coding: utf-8 -*-
#
# ---------------------------------------------------------------------------
# 3.habitatkenmerken - PRJ_Reservegebieden.py
#
# Created on: 25/06/2018
# Last edited on: 03/08/2026 by Nicolas Vanermen
# Last run on: ---
# 
# Version: Python 27
#
# Description: Create tables with all parameter values needed to run the 
# bird model
#
# Remark: generated by ArcGIS/ModelBuilder 
# ---------------------------------------------------------------------------


# -----------------------
# ----- Preparation -----
# -----------------------

# Import modules
import os
import arcpy
from arcpy.sa import *
from arcpy import env

# Check out Spatial Analyst extension
if arcpy.CheckExtension("Spatial") == "Available":
    arcpy.CheckOutExtension("Spatial")
else:
    print("Warning: spatial extension is not available")
    exit()


# --------------------------------------
# ----- Set alternative & scenario -----
# --------------------------------------
print("... Set alternative & scenario")

alternative = "REF_2020"
#scenario = "HIC"
scenario = "Scaldis"

alternative_scenario = alternative + "_" + scenario


# ----------------------------------------------------------
# ----- Set working directory and environment settings -----
# ----------------------------------------------------------
print("... Set working directory and environment settings")

# Set file directories
output_dir = r"Q:\Projects\PRJ_Schelde\ECOTIDE\Vogels\PRJ_Reservegebieden\Output"
data_dir = r"Q:\Projects\PRJ_Schelde\ECOTIDE\Vogels\Basis\Data"
habmap_dir = r"Q:\Projects\PRJ_Schelde\ECOTIDE\Habitats\PRJ_Reservegebieden\Output\Fysiotopen"

# Specify geodatabase to store slope result
vogelmodel_gdb_name = "Vogelmodel_" + alternative_scenario + ".gdb"
vogelmodel_gdb = os.path.join(output_dir, vogelmodel_gdb_name)

if not arcpy.Exists(vogelmodel_gdb):
    arcpy.CreateFileGDB_management(output_dir, vogelmodel_gdb_name)

# Set environment settings
arcpy.env.workspace = arcpy.env.scratchWorkspace = vogelmodel_gdb
env.overwriteOutput = True
env.addOutputsToMap = False


# --------------------
# ------ INPUTS ------
# --------------------
print("... Specify inputs")

habmap_gdb = os.path.join(habmap_dir, "Habitatkaart_IPscen_INBO.gdb")
habmap_kaart = os.path.join(habmap_gdb, "Habmap_2020REF_16B")

DD_gdb_name = "input_DD_" + alternative_scenario + ".gdb"
DD_kaart = os.path.join(output_dir, DD_gdb_name, "Vogelmodel_DD_" + alternative_scenario)

slope_gdb_name = "input_slope_" + alternative_scenario + ".gdb"
slope_kaart = os.path.join(output_dir, slope_gdb_name, "Vogelmodel_slope_" + alternative_scenario)

telgebied_gdb_name = "vogelteltrajecten.gdb"
telgebieden_kaart = os.path.join(data_dir, telgebied_gdb_name, "Vogelteltrajecten_" + alternative)

# --------------------
# ------ OUPUTS ------
# --------------------
print("... Specify outputs")

# output rasters
zacht_intertidaal_en_GGG = "zacht_intertidaal_en_GGG"
telgebieden_zacht_intertidaal_en_GGG_temp = "telgebieden_zacht_intertidaal_en_GGG_temp"
telgebieden_zacht_intertidaal_en_GGG = "telgebieden_zacht_intertidaal_en_GGG"

#output tables
Vogelmodel_slope = "Vogelmodel_slope"
Vogelmodel_DD = "Vogelmodel_DD"

oppervlakte_intertidaal_xls = os.path.join(output_dir, "oppervlakte_intertidaal_" + alternative_scenario + ".xls")
slope_intertidaal_xls = os.path.join(output_dir, "slope_intertidaal_" + alternative_scenario + ".xls")
DD_intertidaal_xls = os.path.join(output_dir, "DD_intertidaal_" + alternative_scenario + ".xls")


# -------------------
# ----- PROCESS -----
# -------------------
print("... Processing")

# selecteer zacht intertidaal en GGG
print("... ... Select mudflats & CRT")
where_clause = "Habmap IS NOT NULL AND Habmap IN ('GGG habitat', 'laag slik', 'middelhoog slik', 'hoog slik')"
arcpy.Select_analysis(habmap_kaart, zacht_intertidaal_en_GGG, where_clause)
arcpy.Intersect_analysis([zacht_intertidaal_en_GGG, telgebieden_kaart], telgebieden_zacht_intertidaal_en_GGG_temp)
arcpy.AlterField_management(telgebieden_zacht_intertidaal_en_GGG_temp, "ZoneCodeOe", "Telgebied", "Telgebied")


# surface intertidaal
print("... ... Calculate surface area")
arcpy.Dissolve_management(
        in_features = telgebieden_zacht_intertidaal_en_GGG_temp,
        out_feature_class = telgebieden_zacht_intertidaal_en_GGG,
        dissolve_field = "Telgebied",
        multi_part = "MULTI_PART"
        )
arcpy.TableToExcel_conversion(telgebieden_zacht_intertidaal_en_GGG, oppervlakte_intertidaal_xls)


# slope intertidaal
print("... ... Calculate slope")
arcpy.sa.ZonalStatisticsAsTable(telgebieden_zacht_intertidaal_en_GGG, "Telgebied", slope_kaart, Vogelmodel_slope, "DATA", "MEAN")
arcpy.TableToExcel_conversion(Vogelmodel_slope, slope_intertidaal_xls)


# DD intertidaal
print("... ... Calculate DD")
arcpy.management.AddField(telgebieden_zacht_intertidaal_en_GGG, "ZoneID", "LONG")
arcpy.management.CalculateField(telgebieden_zacht_intertidaal_en_GGG, "ZoneID", "!OBJECTID!", "PYTHON_9.3")

arcpy.sa.TabulateArea(telgebieden_zacht_intertidaal_en_GGG, "ZoneID", DD_kaart, "Value", Vogelmodel_DD, 1)
arcpy.JoinField_management(Vogelmodel_DD, "ZoneID", telgebieden_zacht_intertidaal_en_GGG, "ZoneID", ["Telgebied"])
arcpy.TableToExcel_conversion(Vogelmodel_DD, DD_intertidaal_xls)

