---
title: "02_HIC_percentielen_LW"
author: "Nicolas"
date: "2026-06-24"
output: html_document
---

```{r Setup, include=FALSE}
library(tidyverse)
library(sf)
library(readxl)
library(purrr)

# --- Paden Definitie ---
path_data          <- "Q:/Projects/PRJ_Schelde/Beheer studie Boven Zeeschelde/Dataverwerking/Habitatmod_opbouw/ScaldismodeloutputWL/hooglaagwater/2013_huidigetoestand/Statistics 4 x QN_2013 plus QE_2013.csv"
path_percentielen  <- "../../../../../Ecotoop/Getij/verwerking/FrequentieHW&LW/outputHWLW/percentielen_HWLW_alle_2010_2013.csv"

path_tijposten_csv    <- "../../Data/Kalibratie/input/tijposten.csv"
path_tijposten_csv2   <- "../../Data/Kalibratie/input/extra_tijposten_Waterinfo.csv"
path_salzone_shp      <- "../../../../../GIS_Zeeschelde/Referentiedata/gebiedsindelingen/ScheldevalleiSalZone_KRW_OMES_2022.shp"
path_alloc_gdb        <- "../../../../../Ecotoop/Fysiotoop/BASIS_Ecotopen_GETIJ_ETRS.gdb"

output_dir <- "../../Output/Kalibratie/"
output_fig <- "../../Output/Kalibratie/extra/darker_shadow/"
```

```{r settings}

# L_H <- "LW"
# 
# percentielen <- c(5, 30, 50)
# 
# title_median_scaldis <- "P30 Scaldis (2013)"
# title_median_HIC     <- "P30 HIC (2010-2013)"
# 
# title_range_scaldis  <- "P5 - P50 Scaldis (2013)"
# title_range_HIC      <- "P5 - P50 HIC (2010-2013)"
# 
# plot_title <- "Kalibratie laagwaterpeilen Scaldis 2013"
# graph_title <- "Kalibratie_LW5_LW50_Zeeschelde_ACT2013.jpg"
# 
# lower_label <- "P5"
# upper_label <- "P50"
# range_y <- c(-1, 3)
 
L_H <- "HW"

percentielen <- c(50, 85, 95)

title_median_scaldis <- "P85 Scaldis (2013)"
title_median_HIC     <- "P85 HIC (2010-2013)"

title_range_scaldis  <- "P50 - P95 Scaldis (2013)"
title_range_HIC      <- "P50 - P95 HIC (2010-2013)"

plot_title <- "Kalibratie hoogwaterpeilen Scaldis 2013"
graph_title <- "Kalibratie_HW50_HW95_Zeeschelde_ACT2013.jpg"

lower_label <- "P95"
upper_label <- "P50"
range_y <- c(4, 6)

```

```{r inladen modeldata}

data_long <- read.csv(path_data, sep = ";") %>%
  rename("percentiel" = "Ofperc",
         "Sint-Amands" = "StAmands.proxy") %>%
  rename_with(~ str_remove(., "\\.proxy$|\\.real$"))  %>%
  mutate(across(everything(), ~ str_remove(., "%$"))) %>%
  filter(percentiel %in% percentielen, HWLW == L_H) %>% 
  select(!c(stat, HWLW, Bath, Zandvliet, Boom, Walem, Duffel.sluis, Lier.Molbrug, Lier.Maasfort, Emblem, Kessel, Hombeek)) %>% 
  pivot_longer(cols = -c(percentiel), names_to = "tijpost", values_to = "waterstand_WL") %>% 
  mutate(percentiel = as.integer(percentiel),
         waterstand_WL = as.numeric(waterstand_WL))

```

```{r inladen tijpostdata}

tijpost_raw <- rbind(
  read.csv(path_tijposten_csv),
  read.csv2(path_tijposten_csv2)) %>%
  mutate(tijpost = if_else(tijpost == "Wintam Sluis", "Wintam Sluis Afwaarts", tijpost))

sf_zones <- st_read(path_salzone_shp, quiet = TRUE)
sf_alloc <- st_read(dsn = path_alloc_gdb, layer = "AllocatieAspntScheldeRupelbekkenETRS", quiet = TRUE) %>% 
  select(AllocNR, Dist)

sf_data_clean <- st_as_sf(tijpost_raw, coords = c("x_lambert72", "y_lambert72"), crs = 31370) %>%
  st_transform(st_crs(sf_zones)) %>%
  st_join(sf_zones %>% select(SalZone)) %>%
  st_transform(st_crs(sf_alloc)) %>%
  st_join(sf_alloc) %>%
  st_drop_geometry() %>%
  mutate(
    SalZone = case_match(SalZone, 
                         c("Mesohalien", "Zone met sterke saliniteitsgradiënt") ~ "brak", .default = "zoet"),
    AllocNR = as.character(as.integer(AllocNR))) %>%
  distinct(tijpost, .keep_all = TRUE)

```

```{r inladen HIC data}

df_hic_raw <- read.csv(path_percentielen, sep=";") %>%
  filter(fase == L_H)

# zijrivieren <- read.csv2(path_percentielen_zijrivieren, sep= ";") %>%
#   filter(fase == "LW")  

# df_hic_raw <- rbind(df_hic_raw, zijrivieren)

rivier_groepen <- list(
  "Zeeschelde" = "Zeeschelde")

```

```{r inladen HIC data}

df_hic_percentiel <- df_hic_raw %>%
  group_by(tijpost, percentiel) %>%
  summarize(waterstand_HIC_gem = mean(waterstand, na.rm = TRUE), .groups = "drop") %>%
  mutate(percentiel = case_when(L_H == "HW" ~ 100 - percentiel, .default = percentiel)) %>% 
  filter(percentiel %in% percentielen) 

df_validation_percentiel <- sf_data_clean %>%
  left_join(
    df_hic_percentiel %>% 
      select(tijpost, percentiel, waterstand_HIC = waterstand_HIC_gem), 
    by = "tijpost") %>%
  left_join(data_long, by = c("tijpost", "percentiel"), relationship = "many-to-many") %>%
  filter(rivier == "Zeeschelde", !tijpost %in% c("Wetteren")) %>%
  filter(!is.na(waterstand_HIC))

```

```{r plot meerdere percentielen}

df_wide <- df_validation_percentiel %>%
  filter(!is.na(waterstand_WL), !tijpost %in% c("Schelle")) %>%
  pivot_wider(
    names_from = percentiel, 
    values_from = c(waterstand_WL, waterstand_HIC),
    names_sep = "_") %>% 
  arrange(Dist)

new_col_names <- c("WL_lower", "WL_median", "WL_upper",
  "HIC_lower", "HIC_median", "HIC_upper")  
  
df_wide <- df_wide %>%
  rename_with(~ new_col_names, last_col(offset = 5):last_col())

stations_as <- df_wide %>% 
  distinct(tijpost, Dist) %>% 
  arrange(Dist)

df_labels <- df_wide %>%
  filter(Dist == max(Dist))

p <- ggplot(df_wide, aes(x = Dist / 1000)) +
  
  geom_ribbon(aes(ymin = WL_lower, ymax = WL_upper, fill = "Scaldis_range"), alpha = 0.25) +
  geom_ribbon(aes(ymin = HIC_lower, ymax = HIC_upper, fill = "HIC_range"), alpha = 0.25) +
  
  geom_line(aes(y = WL_median, color = "Scaldis_median"), linewidth = 0.3) +
  geom_point(aes(y = WL_median, color = "Scaldis_median"), size = 1) +
  
  geom_line(aes(y = HIC_median, color = "HIC_median"), linewidth = 0.3) +
  geom_point(aes(y = HIC_median, color = "HIC_median"), size = 1) +
  
  geom_text(data = df_labels, aes(x = Dist / 1000, y = WL_lower, label = lower_label), 
            hjust = -0.3, vjust = 0.5, size = 2, color = "deepskyblue4") +
  geom_text(data = df_labels, aes(x = Dist / 1000, y = WL_upper, label = upper_label), 
            hjust = -0.3, vjust = 0.5, size = 2, color = "deepskyblue4") +
  
  geom_text(data = df_labels, aes(x = Dist / 1000, y = HIC_lower, label = lower_label), 
            hjust = -0.3, vjust = 0.5, size = 2, color = "orange4") +
  geom_text(data = df_labels, aes(x = Dist / 1000, y = HIC_upper, label = upper_label), 
            hjust = -0.3, vjust = 0.5, size = 2, color = "orange4") +
  
  scale_color_manual(
    name = "",
    values = c("Scaldis_median" = "deepskyblue4", "HIC_median" = "orange4"),
    labels = c("Scaldis_median" = title_median_scaldis, "HIC_median" = title_median_HIC)) +
  
  scale_fill_manual(
    name = "",
    values = c("Scaldis_range" = "deepskyblue4", "HIC_range" = "orange4"),
    labels = c("Scaldis_range" = title_range_scaldis, "HIC_range" = title_range_HIC)) +
  
  scale_x_continuous(breaks = stations_as$Dist / 1000, labels = stations_as$tijpost) +
  scale_y_continuous(limits = range_y) +
  
  theme_bw() +
  
  labs(
    title = plot_title,
    x = "Tijposten", 
    y = "Waterstand (m TAW)") +
  
  theme(
    axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1, size = 8),
    legend.position = "right") +
  
  guides(
    color = guide_legend(order = 1),
    fill = guide_legend(order = 2)
  )

ggsave(paste0(output_fig, graph_title), width = 10, height = 6)

print(p)

```











